[package]
name = "webpage-watcher"
version = "0.1.0"
authors = ["wasuken <wevorence@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "*"
tendril = "*"
scraper = "*"
curl = "*"
